import { Familjen_Grotesk } from "next/font/google";
import "./globals.css";

const familjen = Familjen_Grotesk({ subsets: ["latin"], weight: "400" });

export const metadata = {
	title: "Tienda Virtual Propaganda",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {

	return (
		<html lang="en">
			<head>
				<link rel="stylesheet" href="https://unpkg.com/primeflex@latest/primeflex.css" />
			</head>
			<body className={familjen.className}>
				{children}
			</body>
		</html>
	);
}
